.PHONY: clean All

All:
	@echo "----------Building project:[ Section2.2.1-Exercise2.10 - Debug ]----------"
	@cd "Section2.2.1-Exercise2.10" && "$(MAKE)" -f  "Section2.2.1-Exercise2.10.mk"
clean:
	@echo "----------Cleaning project:[ Section2.2.1-Exercise2.10 - Debug ]----------"
	@cd "Section2.2.1-Exercise2.10" && "$(MAKE)" -f  "Section2.2.1-Exercise2.10.mk" clean
