.PHONY: clean All

All:
	@echo "----------Building project:[ Section1.6-TheBookstoreProgram - Debug ]----------"
	@cd "Section1.6-TheBookstoreProgram" && "$(MAKE)" -f  "Section1.6-TheBookstoreProgram.mk"
clean:
	@echo "----------Cleaning project:[ Section1.6-TheBookstoreProgram - Debug ]----------"
	@cd "Section1.6-TheBookstoreProgram" && "$(MAKE)" -f  "Section1.6-TheBookstoreProgram.mk" clean
